/** Passi del tour guidato — route null = resta sulla pagina corrente */
export const TOUR_STEPS = [
  {
    id: 'welcome',
    route: '/dashboard',
    selector: null,
    title: 'Benvenuto in LeadOS',
    body: 'LeadOS è per qualsiasi attività con clienti da seguire: studi, artigiani, giardinieri, negozi e altro. In pochi minuti scopri pagamenti, preferiti, solleciti e Leo. Puoi uscire con «Salta tour».',
    placement: 'center',
  },
  {
    id: 'sidebar',
    route: '/dashboard',
    selector: '[data-tour="sidebar-nav"]',
    title: 'Menu principale',
    body: 'Dashboard, Lead, Preventivi, Ricevute, Impostazioni e Piano (Stripe). Tutto da qui.',
    placement: 'right',
  },
  {
    id: 'dashboard-payments',
    route: '/dashboard',
    selector: '[data-tour="dashboard-payments"]',
    title: 'Incassi e scadenze',
    body: 'Vedi quanto devi ancora incassare, quante ricevute sono scadute e il totale incassato nel mese corrente.',
    placement: 'bottom',
    fallbackCenter: true,
  },
  {
    id: 'dashboard-revenue',
    route: '/dashboard',
    selector: '[data-tour="dashboard-revenue-chart"]',
    title: 'Grafico fatturato',
    body: 'Le barre mostrano ricevute pagate per mese; in alternativa i lead Conclusi con prezzo. Segna Pagata o Concluso per aggiornare il grafico.',
    placement: 'top',
    fallbackCenter: true,
  },
  {
    id: 'dashboard',
    route: '/dashboard',
    selector: '[data-tour="dashboard-import"]',
    title: 'Importa lead',
    body: 'Trascina un file Excel per importare contatti in blocco. Sotto trovi grafici e promemoria di follow-up.',
    placement: 'bottom',
  },
  {
    id: 'lead-actions',
    route: '/lead',
    selector: '[data-tour="lead-actions"]',
    title: 'Gestione Lead',
    body: 'Aggiungi un contatto o importa Excel. Seleziona più lead per inviare ricevute in blocco.',
    placement: 'bottom',
  },
  {
    id: 'lead-filters',
    route: '/lead',
    selector: '[data-tour="lead-filters"]',
    title: 'Preferiti e filtri rapidi',
    body: 'Filtra per Preferiti, follow-up di oggi o lead senza email. La stella in tabella segna i contatti importanti.',
    placement: 'bottom',
    fallbackCenter: true,
    try: {
      prompt: 'Seleziona un filtro rapido nell’area evidenziata.',
      match: '[data-tour="lead-filters"] button',
      done: 'Filtro applicato.',
    },
  },
  {
    id: 'lead-contacts',
    route: '/lead',
    selector: '[data-tour="lead-contacts"]',
    title: 'Contatti e scheda lead',
    body: 'Email, chiamata e WhatsApp in tabella. Clic sul nome: note, template WhatsApp, copia scheda, duplica lead e storico ricevute.',
    placement: 'bottom',
  },
  {
    id: 'lead-views',
    route: '/lead',
    selector: '[data-tour="lead-views"]',
    title: 'Tabella o Kanban',
    body: 'Passa dalla tabella alla bacheca Kanban e trascina i lead tra gli stati (Nuovo → Concluso).',
    placement: 'left',
    try: {
      prompt: 'Apri la vista Kanban con l’icona a griglia.',
      match: '[data-tour="lead-kanban-btn"]',
      done: 'Vista Kanban attiva.',
    },
  },
  {
    id: 'preventivi',
    route: '/preventivi',
    selector: '[data-tour="preventivi-header"]',
    title: 'Preventivi',
    body: 'Crea preventivi PDF con IVA predefinita dalle Impostazioni. Invia via email e converti in ricevuta se accettato.',
    placement: 'bottom',
  },
  {
    id: 'ricevute',
    route: '/ricevute',
    selector: '[data-tour="ricevute-header"]',
    title: 'Ricevute e pagamenti',
    body: 'Storico invii, badge Pagata/Scaduta, sollecito email o WhatsApp se non pagata, ed Esporta CSV per il commercialista.',
    placement: 'bottom',
    fallbackCenter: true,
  },
  {
    id: 'leo',
    route: '/dashboard',
    selector: '[data-tour="leo-fab"]',
    title: 'Leo — assistente AI',
    body: 'Pulsante viola in basso a destra: bozze email, follow-up e riepiloghi (piani Pro/Agency).',
    placement: 'top',
  },
  {
    id: 'settings',
    route: '/impostazioni',
    selector: '[data-tour="impostazioni-header"]',
    title: 'Profilo azienda',
    body: 'Logo, P.IVA, IBAN e tema PDF. Servono per ricevute valide e email professionali.',
    placement: 'bottom',
  },
  {
    id: 'settings-iva',
    route: '/impostazioni',
    selector: '[data-tour="impostazioni-iva"]',
    title: 'IVA predefinita',
    body: 'Scegli l’aliquota usata di default quando invii ricevute o crei un nuovo preventivo (forfettario → 0%).',
    placement: 'bottom',
    fallbackCenter: true,
  },
  {
    id: 'done',
    route: '/dashboard',
    selector: null,
    title: 'Sei pronto',
    body: 'Importa i lead o aggiungine uno. Rivedi il tour da Impostazioni → «Rivedi tour guidato».',
    placement: 'center',
  },
]
